version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: ${DOCKER_USERNAME}/national_hospital_information:latest
    container_name: national_hospital_information_container
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql

networks:
  my_network:

volumes:
  db_data: