version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: national_hospital_information_db
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: minry20415/national_hospital_information:latest
    container_name: national_hospital_information
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${SECRET_KEY}
    networks:
      - my_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: