spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
    open-in-view: false
    # 대량 데이터 DB INSERT 최적화 설정
    properties:
      jdbc:
        batch_size: 1000 # 1000개씩 Batch Insert 실행
      order_inserts: true # Insert 성능 최적화
      order_updates: true # Update 성능 최적화

jwt:
  token:
    secret: ${SECRET_KEY}

logging:
  level:
    root: info
    com.mk: debug

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
  default-flat-param-object: true