spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  token:
    secret: ${SECRET_KEY}

logging:
  level:
    root: info
    com.mk: debug

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha