name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          ./gradlew clean build

      - name: Build Docker Image
        run: docker build -t national_hospital_information:latest .

      - name: Tag Docker Image
        run: docker tag national_hospital_information:latest ${{ secrets.DOCKER_USERNAME }}/national_hospital_information:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/national_hospital_information:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            export MYSQL_URL=${{ secrets.MYSQL_URL }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_DB=${{ secrets.MYSQL_DB }}
            
            docker stop national_hospital_information_container || true
            docker rm national_hospital_information_container || true
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/national_hospital_information:latest
            
            docker-compose -f /home/ubuntu/docker-compose/docker-compose.yml up -d

      - name: Check if container is running
        run: |
          docker ps -q -f name=national_hospital_information_container
          if [ $? -ne 0 ]; then
            echo "Container is not running"
            exit 1
          fi
